travis:
  secure:
    BINSTAR_TOKEN: qFMvY9oEwEQqIxERGshwuhtZ08Pgm/0EkIhZdQaoV/NHTyqfwEKqr/AOqfoPGtWLLHXBJlBh83C2smuNCtnAdyWrEy1JTn3AFBrgmwyN5WI+uzV3AK+oZqno8WyIaOC9yvHA/qZNshZKJkm8mUooUZRUVo6qg9uq0XxTavVkCN9Kb3VfnJ83aCCXPFZUFNNRL5NbGiUq0cOuALCO7jKJWCQ83MhDK+ZIHQRWrqvMId3yLyU88CCpp5kt9YjZmt7YWgznpx2+FlgdchHzCdoECByZB4TqBpdLvTx7m2OWf85bi8jtqnVEQG0IWYfKQEOp8IKlZTcRd1lkOYxueDrIGZp629ci8B1Ht0JX7NQOOFIt0OAvRe4+y5ktb0eK1rv3c+UfQwK8XzTOyX8OX3Ri4HY7CQnOe1vVd77lFodZbUnEIMpPF/C84DGGu1G61GBIE1rVmTFA/pOA+BIJ3ivmCP9z1v2c10EwW9MAyKJFPdaXsLq1uXjGZmbq74afVUeZdVxLlPmNODtqBBFqXhQ+a2zjDMPGkSHBMh1orIE0SLGC7sA8hJZO8t24mJLomzZD/rFw+ktIZLphIGcwk7WyKCN9PNoy6wHqcb6xDiBB1xR38xqeQdXj3JlWZuPEZye+HvIXS5xt973V2tSzeXr9pcKXALaFDMssHCRhRngWntY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
